"""
Offline commercial license key generation & verification for IronClad
Sentinel, built on Ed25519 signatures.

How the business model actually works end to end:

  1. YOU (the vendor) run `python -m ironclad.licensing.keygen init-keypair`
     ONCE, ever, on your own trusted machine. This produces:
       - `vendor_private_key.pem`  (KEEP SECRET, never ship this to
         customers, never commit it to a public repo)
       - `ironclad/licensing/vendor_public_key.pem` (ships inside the
         product; used only to VERIFY signatures, not create them)

  2. When a customer pays you, you run:
       python -m ironclad.licensing.keygen issue-license \
         --customer "Acme Corp" --seats 25 --days 365 \
         --tier enterprise --private-key vendor_private_key.pem
     This produces a small `license.json` file containing the license
     terms plus an Ed25519 signature over those terms.

  3. You email that `license.json` to the customer. They place it at
     `~/.ironclad/license.json` (or point to it via `--license-file` /
     `IRONCLAD_LICENSE_FILE`).

  4. Every time the CLI runs, `verify_license()` checks the signature
     using the PUBLIC key bundled in the package -- entirely offline,
     no license server, no phone-home, no internet required. This is
     exactly what makes the product deployable into air-gapped/regulated
     customer environments, which is a major selling point for this
     category of tool.

Because verification never calls out to a server, there's no ongoing
hosting cost, no API to keep alive, and no way for a network outage
(customer-side or yours) to ever break the product. Revenue comes purely
from `issue-license` transactions you run locally when someone pays.
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import time
from dataclasses import asdict, dataclass
from typing import Optional

from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives import serialization
from cryptography.exceptions import InvalidSignature

_PACKAGE_DIR = os.path.dirname(__file__)
PUBLIC_KEY_PATH = os.path.join(_PACKAGE_DIR, "vendor_public_key.pem")

DEFAULT_LICENSE_SEARCH_PATHS = [
    os.environ.get("IRONCLAD_LICENSE_FILE", ""),
    os.path.expanduser("~/.ironclad/license.json"),
    os.path.join(os.getcwd(), "license.json"),
    "/etc/ironclad/license.json",
]

VALID_TIERS = {"trial", "standard", "professional", "enterprise"}


@dataclass
class LicenseTerms:
    customer: str
    tier: str
    seats: int
    issued_at: float
    expires_at: float
    license_id: str
    product: str = "IronClad Sentinel"

    def to_canonical_json(self) -> str:
        # Sort keys and use compact separators so signer and verifier
        # always hash byte-identical representations.
        return json.dumps(asdict(self), sort_keys=True, separators=(",", ":"))


def generate_vendor_keypair(private_key_out: str, public_key_out: str) -> None:
    private_key = Ed25519PrivateKey.generate()
    public_key = private_key.public_key()

    private_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_bytes = public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    with open(private_key_out, "wb") as fh:
        fh.write(private_bytes)
    os.chmod(private_key_out, 0o600)

    os.makedirs(os.path.dirname(public_key_out) or ".", exist_ok=True)
    with open(public_key_out, "wb") as fh:
        fh.write(public_bytes)

    print(f"[+] Vendor private key written to: {private_key_out}  (KEEP THIS SECRET, back it up offline)")
    print(f"[+] Vendor public key written to:  {public_key_out}  (this ships inside the product)")


def issue_license(customer: str, tier: str, seats: int, days: int, private_key_path: str,
                   out_path: str) -> str:
    if tier not in VALID_TIERS:
        raise ValueError(f"tier must be one of {VALID_TIERS}")

    with open(private_key_path, "rb") as fh:
        private_key = serialization.load_pem_private_key(fh.read(), password=None)
    if not isinstance(private_key, Ed25519PrivateKey):
        raise ValueError("Private key file is not an Ed25519 key generated by init-keypair.")

    now = time.time()
    terms = LicenseTerms(
        customer=customer,
        tier=tier,
        seats=seats,
        issued_at=now,
        expires_at=now + days * 86400,
        license_id=base64.urlsafe_b64encode(os.urandom(9)).decode("ascii").rstrip("="),
    )

    payload = terms.to_canonical_json().encode("utf-8")
    signature = private_key.sign(payload)

    license_doc = {
        "terms": asdict(terms),
        "signature": base64.b64encode(signature).decode("ascii"),
        "sig_alg": "Ed25519",
    }

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(license_doc, fh, indent=2)

    print(f"[+] License issued for '{customer}' ({tier}, {seats} seats, {days} days) -> {out_path}")
    print(f"    License ID: {terms.license_id}")
    return out_path


class LicenseError(Exception):
    pass


@dataclass
class LicenseStatus:
    valid: bool
    reason: str
    terms: Optional[LicenseTerms] = None
    days_remaining: Optional[int] = None


def _load_public_key() -> Ed25519PublicKey:
    with open(PUBLIC_KEY_PATH, "rb") as fh:
        key = serialization.load_pem_public_key(fh.read())
    if not isinstance(key, Ed25519PublicKey):
        raise LicenseError("Bundled vendor public key is invalid.")
    return key


def find_license_file() -> Optional[str]:
    for path in DEFAULT_LICENSE_SEARCH_PATHS:
        if path and os.path.isfile(path):
            return path
    return None


def verify_license(license_path: Optional[str] = None) -> LicenseStatus:
    path = license_path or find_license_file()
    if not path:
        return LicenseStatus(valid=False, reason="No license file found. Run in trial mode or install a license.json.")

    if not os.path.isfile(path):
        return LicenseStatus(valid=False, reason=f"No license file found at '{path}'. Run in trial mode or install a license.json.")

    try:
        with open(path, "r", encoding="utf-8") as fh:
            doc = json.load(fh)
        terms_dict = doc["terms"]
        signature = base64.b64decode(doc["signature"])
    except (OSError, json.JSONDecodeError, KeyError, ValueError):
        return LicenseStatus(valid=False, reason="License file is malformed or unreadable.")

    terms = LicenseTerms(**terms_dict)
    payload = terms.to_canonical_json().encode("utf-8")

    try:
        public_key = _load_public_key()
        public_key.verify(signature, payload)
    except (InvalidSignature, LicenseError):
        return LicenseStatus(valid=False, reason="License signature is invalid -- file has been tampered with or is not a genuine license.")
    except FileNotFoundError:
        return LicenseStatus(valid=False, reason="Vendor public key missing from installation -- corrupted install.")

    now = time.time()
    if now > terms.expires_at:
        days_expired = int((now - terms.expires_at) / 86400)
        return LicenseStatus(valid=False, reason=f"License expired {days_expired} day(s) ago.", terms=terms)

    days_remaining = int((terms.expires_at - now) / 86400)
    return LicenseStatus(valid=True, reason="OK", terms=terms, days_remaining=days_remaining)


def _cli():
    parser = argparse.ArgumentParser(prog="ironclad-licensing", description="IronClad Sentinel offline license management")
    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init-keypair", help="Generate a new vendor signing keypair (run ONCE, keep private key secret)")
    p_init.add_argument("--private-key", default="vendor_private_key.pem")
    p_init.add_argument("--public-key", default=PUBLIC_KEY_PATH)

    p_issue = sub.add_parser("issue-license", help="Issue a signed license file for a paying customer")
    p_issue.add_argument("--customer", required=True)
    p_issue.add_argument("--tier", required=True, choices=sorted(VALID_TIERS))
    p_issue.add_argument("--seats", type=int, default=10)
    p_issue.add_argument("--days", type=int, default=365)
    p_issue.add_argument("--private-key", required=True)
    p_issue.add_argument("--out", default="license.json")

    p_verify = sub.add_parser("verify", help="Verify a license file (same check the CLI runs at scan time)")
    p_verify.add_argument("--license-file", default=None)

    args = parser.parse_args()

    if args.command == "init-keypair":
        generate_vendor_keypair(args.private_key, args.public_key)
    elif args.command == "issue-license":
        issue_license(args.customer, args.tier, args.seats, args.days, args.private_key, args.out)
    elif args.command == "verify":
        status = verify_license(args.license_file)
        if status.valid:
            print(f"[OK] Valid license for '{status.terms.customer}' ({status.terms.tier}). {status.days_remaining} day(s) remaining.")
        else:
            print(f"[INVALID] {status.reason}")


if __name__ == "__main__":
    _cli()
